// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForTest.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ForTest.proto</summary>
public static partial class ForTestReflection {

  #region Descriptor
  /// <summary>File descriptor for ForTest.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ForTestReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1Gb3JUZXN0LnByb3RvGhlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvIkYK",
          "B0ZvclRlc3QSFAoMc2FtcGxlU3RyaW5nGAEgASgJEiUKB2RldGFpbHMYAiAD",
          "KAsyFC5nb29nbGUucHJvdG9idWYuQW55YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ForTest), global::ForTest.Parser, new[]{ "SampleString", "Details" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ForTest : pb::IMessage<ForTest> {
  private static readonly pb::MessageParser<ForTest> _parser = new pb::MessageParser<ForTest>(() => new ForTest());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ForTest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ForTestReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ForTest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ForTest(ForTest other) : this() {
    sampleString_ = other.sampleString_;
    details_ = other.details_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ForTest Clone() {
    return new ForTest(this);
  }

  /// <summary>Field number for the "sampleString" field.</summary>
  public const int SampleStringFieldNumber = 1;
  private string sampleString_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SampleString {
    get { return sampleString_; }
    set {
      sampleString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "details" field.</summary>
  public const int DetailsFieldNumber = 2;
  private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Any> _repeated_details_codec
      = pb::FieldCodec.ForMessage(18, global::Google.Protobuf.WellKnownTypes.Any.Parser);
  private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> details_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> Details {
    get { return details_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ForTest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ForTest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SampleString != other.SampleString) return false;
    if(!details_.Equals(other.details_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (SampleString.Length != 0) hash ^= SampleString.GetHashCode();
    hash ^= details_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (SampleString.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SampleString);
    }
    details_.WriteTo(output, _repeated_details_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (SampleString.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SampleString);
    }
    size += details_.CalculateSize(_repeated_details_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ForTest other) {
    if (other == null) {
      return;
    }
    if (other.SampleString.Length != 0) {
      SampleString = other.SampleString;
    }
    details_.Add(other.details_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          SampleString = input.ReadString();
          break;
        }
        case 18: {
          details_.AddEntriesFrom(input, _repeated_details_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
